### ISSUE TITLE
Stosowanie getterow/setterow w encjach a lombook

### ISSUE THREAD

**Issue by CezaryJanicki** [pplutap/jdp-2012-01#17]
Wstepnie mozemy rozpoczac dyskusje co jest lepiej, aby usystematyzowac dalsza prace. Czy stosujemy pisanie gettterow/setterow czy wystarczy lombook w encjach. Poddaje pod dyskusje.

**Comment by mac-stuff** [comment]
Ja jestem za minimalizowaniem ilości linijek kodu, dlatego zdecydowanie głosuję na Lombok

**Comment by BarcaLS** [comment]
Mnie w sumie wszystko jedno, byle było tak samo. Jak mam głosować to Lombok.

**Comment by CezaryJanicki** [comment]
Ja tez jestem za Lombokiem. W takim razie trzeba będzie przepisać klasy. Czy tworzymy nowe zadania w Jirze? Pod tytułem zmiana na Lomboka?

**Comment by BarcaLS** [comment]
Ja już zmieniłem Product na Lomboka przy okazji implementacji ProductControllera - nie widziałem potrzeby robienia osobnego zadania.

**Comment by CezaryJanicki** [comment]
Ok. Zamykam dyskusje. Stosujemy Lomboka.
