### ISSUE TITLE
RequestMapping vs GetMapping/PostMapping/PutMapping

### ISSUE THREAD

**Issue by CezaryJanicki** [pplutap/jdp-2012-01#23]
Tak jak wczesniej, pytam o zdanie co stosujemy? Mamy dwie opcje - RequestMapping z adnotacja lub GetMapping/PostMapping etc. Prosze o info.

**Comment by BarcaLS** [comment]
Osobiście uważam, że nie ma tego potrzeby unifikować bo to tylko konwencja: "Specifically, @PostMapping is a composed annotation that acts as a shortcut for @RequestMapping(method = RequestMethod.POST)".
Ale jakby co to głos za RequestMapping bo:
1) użyłem tego (hehe)
2) a użyłem tego bo to jest bardziej ogólny sposób, jedna adnotacja z parametrem zamiast kilku adnotacji do nauki :)
